dojosecrets/apps/logreg/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^register$', views.register, name = 'register'),
    url(r'^logout$',views.logout, name = 'logout')
]

dojosecrets/apps/main_app/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^secrets$', views.secrets, name = 'secrets'),
    url(r'^addSecret$', views.addSecret, name = 'addsecret'),
    url(r'^(?P<id>\d+)/addLike$', views.addLike, name = 'addlike'),
    url(r'^allsecrets$', views.allsecrets, name = 'allsecrets'),
    url(r'^(?P<id>\d+)/delete$', views.deletesecret, name = 'delete')
]

dojosecrets/dojosecrets/urls.py
from django.conf.urls import url,include
# from django.contrib import admin

urlpatterns = [
    url(r'^',include("apps.logreg.urls", namespace='logreg')),
    url(r'^main/',include("apps.main_app.urls", namespace='main')),
]

dojosecrets/apps/logreg/models.py
from __future__ import unicode_literals

from django.db import models

import re, bcrypt

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
# Create your models here.

class UserManager(models.Manager):
    def register_user(self,postData):
        errors = []
        if len(postData['first_name']) < 2:
            errors.append('First name must be at least 2 characters long')

        if len(postData['last_name']) < 2:
            errors.append('Last name must be at least 2 characters long')

        if not len(postData['email']):
            errors.append('Email is required')
        else:
            if not EMAIL_REGEX.match(postData['email']):
                errors.append('Enter a valid email')

        if len(postData['password']) < 8:
            errors.append('Password must be at least 8 characters long')

        if not postData['password']  == postData['confirm_password']:
            errors.append("Confirm Password doesn't match Password")

        if self.filter(email = postData['email']):
            errors.append('This email already belongs to a user')

        response_to_views = {}
        if not errors:
            hashed_password = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())
            user = self.create(first_name = postData['first_name'], last_name = postData['last_name'], email = postData['email'], password = hashed_password)
            response_to_views['user'] = user
            response_to_views['status'] = True
        else:
            response_to_views['errors'] = errors
            response_to_views['status'] = False

        return response_to_views

    def login_user(self,postData):
        user = self.filter(email = postData['email'])
        response_to_views = {}

        if not user:
            response_to_views['status'] = False
            response_to_views['errors'] = 'Email address not found'
        else:
            if bcrypt.checkpw(postData['password'].encode(), user[0].password.encode()):
                response_to_views['status'] = True
                response_to_views['user'] = user.first()
            else:
                response_to_views['status'] = False
                response_to_views['errors'] = 'Invalid Email/password combination'

        return response_to_views


class User(models.Model):
    first_name = models.CharField(max_length = 45)
    last_name = models.CharField(max_length = 45)
    email = models.CharField(max_length = 255)
    password = models.CharField(max_length = 255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = UserManager()

dojosecrets/apps/main_app/models.py
from __future__ import unicode_literals

from django.db import models
from ..logreg.models import User
# Create your models here.

class SecretManager(models.Manager):
    def validateSecret(self,postData, user_id):
        errors = []
        if not len(postData['secret']):
            errors.append('Please add something to your secret post')

        response_to_views ={}

        if errors:
            response_to_views['status'] = False
            response_to_views['errors'] = errors
        else:
            print "user_id",user_id
            this_creator = User.objects.get(id = user_id)
            secret = self.create(secret = postData['secret'], user = this_creator )
            response_to_views['status'] = True
            response_to_views['secret'] = secret

        return response_to_views

    def validateLike(self,user_id,secret_id):
        response_to_views ={}
        user = User.objects.get(id = user_id)
        print user.id
        secret = Secret.objects.get(id = secret_id)
        print secret.id
        if user in secret.likes.all() :
            print "inside like condition"
            response_to_views['status'] = False
        else:
            print "inside else condition"
            this_secret = Secret.objects.get(id = secret_id)
            this_liker = User.objects.get(id = user_id)
            this_secret.likes.add(this_liker)
            response_to_views['status'] = True
            
        return response_to_views


class Secret(models.Model):
    secret = models.CharField(max_length = 45)
    likes = models.ManyToManyField(User,related_name = "likes")
    user = models.ForeignKey(User, related_name = 'created_by')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = SecretManager()

dojosecrets/apps/logreg/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .models import User

# Create your views here.

def index(request):
    context = {
    }
    return render(request,'logreg/index.html',context)

def login(request):
    response_from_models = User.objects.login_user(request.POST)

    if response_from_models['status']:
        request.session['user_id'] = response_from_models['user'].id

        return redirect('main:secrets')
    else:
        messages.error(request, response_from_models['errors'])
        return redirect('logreg:index')


def register(request):
    response_from_models = User.objects.register_user(request.POST)

    if response_from_models['status']:
        request.session['user_id'] = response_from_models['user'].id

        return redirect('main:secrets')
    else:
        for error in response_from_models['errors']:
            messages.error(request, error)

        return redirect('logreg:index')

def logout(request):
    request.session.clear()
    return redirect('logreg:index')

dojosecrets/apps/main_app/views.py
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse
from .models import Secret
from ..logreg.models import User
from django.db.models import Count
# Create your views here.

def secrets(request):
    # var count = 5
    first_5 = []
    count = 0
    order_byTime = Secret.objects.all().order_by('-created_at')

    if len(order_byTime) >= 5:
        while count < 5 :
            print count
            first_5.append(order_byTime[count])
            count = count + 1

    print first_5

    context = {
        "Secrets": first_5,
        "all_secrets": order_byTime,
        "user": User.objects.filter(id = request.session['user_id'])
    }

    return render(request,'main_app/index.html',context)


def addSecret(request):
    response_from_models = Secret.objects.validateSecret(request.POST,request.session['user_id'])

    if response_from_models['status']:
        print "successfully added secret", response_from_models['secret']
        return redirect('main:secrets')
    else:
        print "failed to add secret"
        return redirect('logreg:index')


def addLike(request,id):
    secret_id = id
    response_from_models = Secret.objects.validateLike(request.session['user_id'], secret_id)

    if response_from_models['status']:
        print "successfully added like"
        return redirect('main:secrets')
    else:
        print "failed to add like"
        return redirect('main:secrets')


def allsecrets(request):

    context = {
        "Secrets":Secret.objects.annotate(num_likes = Count("likes")).order_by("-num_likes")
    }

    return render(request,'main_app/allsecrets.html',context)


def deletesecret(request,id):
    Secret.objects.get(id = id).delete()
    return redirect('main:secrets')

dojosecrets/apps/logreg/templates/logreg/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h2>Register</h2>
    {% if messages %}
      {% for message in messages %}
        <ul>
          <li>{{message.message}}</li>
        </ul>
      {% endfor %}
    {% endif %}


    <form class="" action="{% url 'logreg:register' %}" method="post">
      {% csrf_token %}
      <label for="">First Name</label>
      <input type="text" name="first_name" value=""><br>

      <label for="">Last Name</label>
      <input type="text" name="last_name" value=""><br>

      <label for="">Email</label>
      <input type="text" name="email" value=""><br>

      <label for="">Password</label>
      <input type="text" name="password" value=""><br>

      <label for="">Password Confirmation</label>
      <input type="text" name="confirm_password" value=""><br>

      <input type="submit" name="" value="Register!">
    </form>

    <h2>Login</h2>

    <form class="" action="{% url 'logreg:login' %}" method="post">
      {% csrf_token %}
      <label for="">Email</label>
      <input type="text" name="email" value=""><br>

      <label for="">Password</label>
      <input type="text" name="password" value=""><br>

      <input type="submit" name="" value="Login!">
    </form>

  </body>
</html>

dojosecrets/apps/main_app/templates/main_app/allsecrets.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <a href="{% url 'main:secrets' %}">Back</a>
    <h1>Most Popular Secrets</h1>
    {% for secret in Secrets %}
      <p>{{secret.secret}} ({{secret.created_at|timesince}} ago) {{secret.likes.count}} likes<a href="{% url 'main:addlike' id=secret.id %}">Like</a></p>
        <!-- {% for like in secret.likes.all %}
          {{like.first_name}}
        {% endfor %} -->
        {% if secret.user.id == request.session.user_id %}
          <p>You posted this <a href="{% url 'main:delete' id=secret.id %}">Delete</a> </p>
        {% endif %}
        {% for user in secret.likes.all %}
          {% if user.id == request.session.user_id %}
            <p>You liked this</p>
          {% endif %}
        {% endfor %}
    {% endfor %}

    <form class="" action="{% url 'logreg:logout' %}" method="post">
      {% csrf_token %}
      <input type="submit" name="" value="Logout">
    </form>
  </body>
  {% for secret in Secret %}
    {% for like in secret.likes %}
      {{secret.like.first_name}}
    {% endfor %}
  {% endfor %}

</html>

dojosecrets/apps/main_app/templates/main_app/index.html
<h1>Hello {% for user in user %}{{user.first_name}}{% endfor %}</h1>

<form class="" action="{% url 'main:addsecret' %}" method="post">
  {% csrf_token %}
  <textarea name="secret" rows="8" cols="80" placeholder = "Your secret here..."></textarea>
  <input type="submit" name="" value="Post">
</form>
<a href="{% url 'main:allsecrets' %}">Most Popular Secrets</a>
<h1>Recent Secrets: </h1>
{% for secret in Secrets %}
  <p>{{secret.secret}} ({{secret.created_at|timesince}} ago) {{secret.likes.count}} likes<a href="{% url 'main:addlike' id=secret.id %}">Like</a></p>
    {% if secret.user.id == request.session.user_id %}
      <p>You posted this <a href="{% url 'main:delete' id=secret.id %}">Delete</a> </p>
    {% endif %}
    {% for user in secret.likes.all %}
      {% if user.id == request.session.user_id %}
        <p>You liked this</p>
      {% endif %}
    {% endfor %}
{% endfor %}

{% if not Secrets %}
  {% for secret in all_secrets %}
    <p>{{secret.secret}} ({{secret.created_at|timesince}} ago) {{secret.likes.count}} likes<a href="{% url 'main:addlike' id=secret.id %}">Like</a></p>
      {% if secret.user.id == request.session.user_id %}
        <p>You posted this <a href="{% url 'main:delete' id=secret.id %}">Delete</a></p>
      {% endif %}
      {% for user in secret.likes.all %}
        {% if user.id == request.session.user_id %}
          <p>You liked this</p>
        {% endif %}
      {% endfor %}
  {% endfor %}
{% endif %}

<form class="" action="{% url 'logreg:logout' %}" method="post">
  {% csrf_token %}
  <input type="submit" name="" value="Logout">
</form>