wishlist/apps/item/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^additem$', views.additem, name = 'additem'),
    url(r'^(?P<id>\d+)/delete$', views.deleteitem, name = 'delete')
]

wishlist/apps/logreg/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^login$', views.login, name = 'login'),
    url(r'^register$', views.register, name = 'register'),
    url(r'^logout$',views.logout, name = 'logout')
]

wishlist/apps/main_app/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^wishlist$', views.wishlist, name = 'wishlist'),
    url(r'^(?P<id>\d+)/additem$', views.addItem, name = 'additem')
]

wishlist/wishlist/urls.py
from django.conf.urls import url,include
# from django.contrib import admin

urlpatterns = [
    url(r'^',include("apps.logreg.urls", namespace='logreg')),
    url(r'^main/',include("apps.main_app.urls", namespace='main')),
    url(r'^item/',include("apps.item.urls", namespace='item')),
]

wishlist/apps/main_app/models.py
from __future__ import unicode_literals

from django.db import models
from ..logreg.models import User
from ..item.models import Item
# Create your models here.

class WishlistManager(models.Manager):
    def addList(self,user_id):
        print "user_id",user_id
        this_creator = User.objects.get(id = user_id)
        return self.create(user = this_creator )

    def addListItem(self,item_id,user):
        print "item_id", item_id
        item = Item.objects.get(id = item_id)
        print "item.id",item.id
        wishlist = Wishlist.objects.get(user = user)
        print wishlist.id
        wishlist.items.add(item)
        print "success"
        return

class Wishlist(models.Model):
    items = models.ManyToManyField(Item,related_name = "items")
    user = models.OneToOneField(User,related_name = "wishlist")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = WishlistManager()

wishlist/apps/main_app/views.py
from django.shortcuts import render,redirect
from django.core.urlresolvers import reverse
from ..logreg.models import User
from ..main_app.models import Wishlist
from ..item.models import Item
# Create your views here.

def wishlist(request):
    my_wishlists = Wishlist.objects.filter(user = User.objects.filter(id = request.session['user_id']))
    my_items = []
    
    context = {
        "MyWishlist": Wishlist.objects.filter(user = User.objects.filter(id = request.session['user_id'])),
        "user":User.objects.filter(id = request.session['user_id']),
        "all_wishlists": Wishlist.objects.exclude(user = User.objects.get(id = request.session['user_id'])),
        "my_items": my_items,
    }
    return render(request,'main_app/index.html', context)

def addItem(request,id):
    user = User.objects.get(id = request.session['user_id'])
    Wishlist.objects.addListItem(id,user)
    return redirect('main:wishlist')

wishlist/apps/main_app/templates/main_app/index.html
<h1>Hello {% for user in user %}{{user.first_name}}{% endfor %}</h1>

<h2>Your Wish List: </h2>

<table>
  <thead>
    <th>Item</th>
    <th>Added by</th>
    <th>Date Added</th>
    <th>Action</th>
  </thead>

  <tbody>
    {% for wishlist in MyWishlist %}
      {% for item in wishlist.items.all %}
      <tr>
        <td>{{item.item}}</td>
        <td>{{item.user.first_name}}</td>
        <td>{{item.created_at}}</td>
        {% if item.user.id == request.session.user_id %}
          <td><a href="{% url 'item:delete' id=item.id %}">Delete</a></td>
        {% else %}
            <td><a href="#"> Remove item from my wishlist</a></td>
        {% endif %}
      {% endfor %}
    {% endfor %}
      </tr>
  </tbody>

  </table>


<h2>Other Users' Wish List</h2>

<table>
  <thead>
    <th>Item</th>
    <th>Added by</th>
    <th>Date Added</th>
    <th>Action</th>
  </thead>

  <tbody>
    {% for wishlist in all_wishlists %}
      {% for item in wishlist.items.all %}
        {% for wishlist2 in MyWishlist %}
          {% for item2 in wishlist2.items.all %}
            {% if not item.id == item2.id %}
              {% if not item.user.id == request.session.user_id %}
                  <tr>
                    <td>{{item.item}}</td>
                    <td>{{item.user.first_name}}</td>
                    <td>{{item.created_at}}</td>
                    <td><a href="{% url 'main:additem' id=item.id %}">Add item to wishlist</a></td>
                  </tr>
                {% endif %}
              {% endif %}
            {% endfor %}
          {% endfor %}
        {% endfor %}
      {% endfor %}
  </tbody>
</table>
<a href="{% url 'item:index' %}">Add</a>
<form class="" action="{% url 'logreg:logout' %}" method="post">
  {% csrf_token %}
  <input type="submit" name="" value="Logout">
</form>